### ISSUE TITLE
Hi, there i can't contact you on discord 

### ISSUE THREAD

**Issue by imnagarajan** [badolsmito/projtmpl#1]
Please

**Comment by badolsmito** [comment]
badols mito#9161

**Comment by imnagarajan** [comment]
@badolsmito and also can i get the mini game plugin

**Comment by imnagarajan** [comment]
> @badolsmito and also can i get the mini game plugin

If you feel bad to finish the plugin can be update UserSpecificFunctions plugin please

**Comment by imnagarajan** [comment]
I can't find your profile so can you message me @badolsmito GoldenWolf#9191

**Comment by badolsmito** [comment]
1. You have to build the (unfinished, with bad code) plugin yourself.
2. I haven't heard of the UserSpecificFunctions plugin and, frankly, I don't want to work with C# anymore.
3. I ended up deleting my Discord account for personal reasons.

**Comment by imnagarajan** [comment]
Ok 😭
